### ISSUE TITLE
oauth is not working as planned

### ISSUE THREAD

**Issue by Gibbedboy** [julianryorex/EPIIC-Project#7]
Not entirely sure where things are going wrong. Potentially all the things are going wrong.
For now have hardcoded the Google client ID to be used in the first authenticateViaOauth() field. This is highly unsafe, and a stopgap measure for now until more broad issues can be resolved.

**Comment by Gibbedboy** [comment]
Working on service authentication as a solution.

**Comment by julianryorex** [comment]
The service account has been authenticated by Google. The authentication and initialization works.
